trigger:
  - main

pool: slave

stages:
  - stage: CI
    jobs:
      - job: CI
        steps:
          - script: "npm install"
            displayName: Install nodejs dependencies
          - script: "docker build -t ${COMPONENT} ."
            displayName: Build docker image


  - stage: DockerImageUpload
    condition: succeeded()
    jobs:
      - job: ImageUpload
        steps:
          - script: |
              aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 124374336606.dkr.ecr.us-east-1.amazonaws.com
              docker tag ${COMPONENT}:latest 124374336606.dkr.ecr.us-east-1.amazonaws.com/${COMPONENT}:latest
              docker push 124374336606.dkr.ecr.us-east-1.amazonaws.com/${COMPONENT}:latest
            displayName: Docker push image to ECR